services:

  localstack:
    image: localstack/localstack:1.3.1
    environment:
      - AWS_DEFAULT_REGION=eu-west-2
      - EDGE_PORT=4566
      - SERVICES=s3
    ports:
      - "4566-4583:4566-4583"
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"